import type { Listing } from '@/types/listing';

/**
 * Week-1 placeholder data — used until Firestore seeding lands in week 2.
 * Photos are picsum.photos URLs (free, no auth) sized for cards.
 */
export const MOCK_LISTINGS: Listing[] = [
  {
    id: 'lst-001',
    ownerId: 'mock-owner-1',
    ownerRole: 'landlord',
    type: 'single',
    title: 'Quiet single room near UB gate',
    description:
      'Bright single room with steady water and tiled floor. 5-minute walk to the main UB gate. Suitable for a focused student.',
    pricePerYear: 220_000,
    zone: 'Molyko',
    address: 'Off Checkpoint, Molyko',
    geo: { lat: 4.158, lng: 9.286 },
    distanceFromUbMeters: 480,
    amenities: ['water', 'electricity', 'security', 'study_desk'],
    photos: [
      'https://picsum.photos/seed/hostelhub-1a/800/600',
      'https://picsum.photos/seed/hostelhub-1b/800/600',
    ],
    status: 'active',
    verified: true,
    rating: 4.6,
    reviewCount: 12,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 7,
    updatedAt: Date.now() - 1000 * 60 * 60 * 24,
  },
  {
    id: 'lst-002',
    ownerId: 'mock-owner-2',
    ownerRole: 'landlord',
    type: 'studio',
    title: 'Furnished studio with kitchenette',
    description:
      'Modern studio with private bathroom, kitchen corner, and Wi-Fi. Great for students who want privacy and a quiet space to study.',
    pricePerYear: 480_000,
    zone: 'Bonduma',
    address: 'Bonduma Junction',
    geo: { lat: 4.149, lng: 9.272 },
    distanceFromUbMeters: 1450,
    amenities: ['water', 'electricity', 'wifi', 'kitchen', 'bathroom_private', 'furnished'],
    photos: [
      'https://picsum.photos/seed/hostelhub-2a/800/600',
      'https://picsum.photos/seed/hostelhub-2b/800/600',
    ],
    status: 'active',
    verified: true,
    rating: 4.8,
    reviewCount: 28,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 14,
    updatedAt: Date.now() - 1000 * 60 * 60 * 6,
  },
  {
    id: 'lst-003',
    ownerId: 'mock-owner-3',
    ownerRole: 'agent',
    type: 'hostel',
    title: 'Affordable hostel bed, shared room',
    description:
      'Bed space in a 4-person room. Communal kitchen, generator backup, and security 24/7. Best for first-year students on a budget.',
    pricePerYear: 165_000,
    zone: 'Mile 16',
    address: 'Mile 16 main road',
    geo: { lat: 4.139, lng: 9.265 },
    distanceFromUbMeters: 3200,
    amenities: ['water', 'electricity', 'security', 'kitchen', 'generator'],
    photos: [
      'https://picsum.photos/seed/hostelhub-3a/800/600',
      'https://picsum.photos/seed/hostelhub-3b/800/600',
    ],
    status: 'active',
    verified: false,
    rating: 4.1,
    reviewCount: 7,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
    updatedAt: Date.now() - 1000 * 60 * 60 * 12,
  },
  {
    id: 'lst-004',
    ownerId: 'mock-owner-4',
    ownerRole: 'landlord',
    type: 'apartment',
    title: 'Two-bedroom apartment, ideal for roommates',
    description:
      'Spacious 2-bedroom apartment with balcony and parking. Comes furnished. Great for two students or a small family.',
    pricePerYear: 950_000,
    zone: 'Great Soppo',
    address: 'Soppo, behind the market',
    geo: { lat: 4.162, lng: 9.295 },
    distanceFromUbMeters: 1900,
    amenities: ['water', 'electricity', 'wifi', 'parking', 'furnished', 'balcony', 'laundry'],
    photos: [
      'https://picsum.photos/seed/hostelhub-4a/800/600',
      'https://picsum.photos/seed/hostelhub-4b/800/600',
    ],
    status: 'active',
    verified: true,
    rating: 4.9,
    reviewCount: 41,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 21,
    updatedAt: Date.now() - 1000 * 60 * 60 * 2,
  },
  {
    id: 'lst-005',
    ownerId: 'mock-owner-5',
    ownerRole: 'landlord',
    type: 'single',
    title: 'Cozy room with study desk',
    description:
      'Single room in a quiet compound. Includes a desk, wardrobe, and shared kitchen. Walking distance to Molyko food court.',
    pricePerYear: 250_000,
    zone: 'Molyko',
    address: 'Behind Molyko stadium',
    geo: { lat: 4.157, lng: 9.282 },
    distanceFromUbMeters: 650,
    amenities: ['water', 'electricity', 'study_desk', 'kitchen'],
    photos: [
      'https://picsum.photos/seed/hostelhub-5a/800/600',
      'https://picsum.photos/seed/hostelhub-5b/800/600',
    ],
    status: 'active',
    verified: false,
    rating: 4.3,
    reviewCount: 5,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5,
    updatedAt: Date.now() - 1000 * 60 * 60 * 18,
  },
  {
    id: 'lst-006',
    ownerId: 'mock-owner-6',
    ownerRole: 'agent',
    type: 'studio',
    title: 'Studio with private bathroom & balcony',
    description:
      'Self-contained studio with private bathroom, kitchen, and a small balcony overlooking the neighborhood.',
    pricePerYear: 420_000,
    zone: 'Bomaka',
    address: 'Bomaka, off the main road',
    geo: { lat: 4.144, lng: 9.27 },
    distanceFromUbMeters: 2100,
    amenities: ['water', 'electricity', 'wifi', 'bathroom_private', 'balcony', 'kitchen'],
    photos: [
      'https://picsum.photos/seed/hostelhub-6a/800/600',
      'https://picsum.photos/seed/hostelhub-6b/800/600',
    ],
    status: 'active',
    verified: true,
    rating: 4.5,
    reviewCount: 14,
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 10,
    updatedAt: Date.now() - 1000 * 60 * 60 * 4,
  },
];

export function getMockListingById(id: string): Listing | undefined {
  return MOCK_LISTINGS.find((l) => l.id === id);
}
